# typed: false
# frozen_string_literal: true

# Auto-generated by the void release workflow. Do not edit by hand.
class Void < Formula
  desc "One inbox for everything — unified messaging CLI"
  homepage "https://github.com/MaximeGaudin/void"
  version "0.14.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/MaximeGaudin/void/releases/download/0.14.0/void-darwin-arm64.tar.gz"
      sha256 "5f49381ad489ce32b508e027562aca076c11a769998f70fefa1691aeb0bc9d75"
    end
    on_intel do
      url "https://github.com/MaximeGaudin/void/releases/download/0.14.0/void-darwin-amd64.tar.gz"
      sha256 "f4b17760e397c2db5cc90c636f4e2ea46111dae7cb60e394446fb0120f6aa77b"
    end
  end

  def install
    bin.install "void"
  end

  test do
    assert_match "void", shell_output("#{bin}/void --version")
  end
end
