# typed: false
# frozen_string_literal: true

# Auto-generated by the void release workflow. Do not edit by hand.
class Void < Formula
  desc "One inbox for everything — unified messaging CLI"
  homepage "https://github.com/MaximeGaudin/void"
  version "0.11.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/MaximeGaudin/void/releases/download/0.11.0/void-darwin-arm64.tar.gz"
      sha256 "d60eb95db4c2b62fc450c62a8685de113be535a6af9893eb8c40ec9b637ae59e"
    end
    on_intel do
      url "https://github.com/MaximeGaudin/void/releases/download/0.11.0/void-darwin-amd64.tar.gz"
      sha256 "a6f13f5d392c42b4b622eff789a93e4bec719296eab75f029023394bcc040a80"
    end
  end

  def install
    bin.install "void"
  end

  test do
    assert_match "void", shell_output("#{bin}/void --version")
  end
end
